apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"resources.cattle.io/v1","kind":"Backup","metadata":{"annotations":{},"creationTimestamp":"2022-12-21T10:46:05Z","generation":1,"name":"default-location-recurring-backup","resourceVersion":"1592413","uid":"60b45ecb-fb27-41ca-af4f-d1ca0aab83aa"},"spec":{"resourceSetName":"rancher-resource-set"},"status":{"backupType":"One-time","conditions":[{"lastUpdateTime":"2022-12-21T10:46:13Z","message":"Completed","status":"True","type":"Ready"},{"lastUpdateTime":"2022-12-21T10:46:13Z","status":"True","type":"Uploaded"}],"filename":"default-location-recurring-backup-1e8e5bca-5e35-4538-b7cd-0680e8363145-2022-12-21T10-46-05Z.tar.gz","lastSnapshotTs":"2022-12-21T10:46:13Z","nextSnapshotAt":"","observedGeneration":1,"storageLocation":"PV","summary":""}}
  creationTimestamp: "2022-12-21T10:48:41Z"
  generation: 1
  name: default-location-recurring-backup
  resourceVersion: "1593795"
  uid: 86875ffc-76d0-4fa4-bcad-d3fd0a8456d6
spec:
  resourceSetName: rancher-resource-set
status:
  backupType: One-time
  conditions:
  - lastUpdateTime: "2022-12-21T10:48:48Z"
    message: Completed
    status: "True"
    type: Ready
  - lastUpdateTime: "2022-12-21T10:48:48Z"
    status: "True"
    type: Uploaded
  filename: default-location-recurring-backup-1e8e5bca-5e35-4538-b7cd-0680e8363145-2022-12-21T10-48-41Z.tar.gz
  lastSnapshotTs: "2022-12-21T10:48:48Z"
  nextSnapshotAt: ""
  observedGeneration: 1
  storageLocation: PV
  summary: ""
